language: ruby
rvm:
- 2.3.1
install:
- travis_retry bundle install
# script: bundle exec rspec
notifications:
  slack: "$SLACK_TOKEN"
  email: false
deploy:
  provider: rubygems
  api_key:
    secure: 63b5df1bb3cccc852a8735dac74655b0
  gem: kishu
  on:
    tags: true
    repo: datacite/kishu
